Numpy Array Operations


In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3 , 4, 5, 6, 7, 8, 9, 10])
print('Basic slicing: ', arr[2:7])
print('With step: ', arr[1:8:2])
print('Negative indexing: ', arr[-3])

Basic slicing:  [3 4 5 6 7]
With step:  [2 4 6 8]
Negative indexing:  8


In [4]:
arr_2d =np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print('Specific element: ', arr_2d[1, 2])
print('Entire row: ', arr_2d[1])
print('Entire row: ', arr_2d[:,1])


Specific element:  6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print('Sorted Array: ', np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print('Sorted 2D array by column: \n', np.sort(arr_2d_unsorted))

Sorted Array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by column: 
 [[1 3]
 [1 2]
 [2 3]]


Filter 

In [8]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print('Even numbers: ', even_number)

Even numbers:  [ 2  4  6  8 10]


Filter with mask 

In [10]:
mask = numbers > 5
print('Numbers greater than 5: ', numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


Fancy indexing vs np.where()

In [12]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print('NP where', numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [13]:
condition_array = np.where(numbers > 5, 'true', 'false')
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Adding and removing data 

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


Array compatibility

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print('Compatibility shapes', a.shape == b.shape)

Compatibility shapes False


In [16]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print('With new column', with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print('Array after deletion: ', deleted)

Array after deletion:  [1 2 4 5]
