### NumPy array and basics

In [2]:
import numpy as np

print(np.__version__)

2.5.2


In [3]:
a = 5
b = 4

a + b

9

Creating array from list 

In [4]:
arr_1d = np.array([1,2,3,4,5])
print('1D array: ', arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print('2D array: ', arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


List vs numpy array 

In [5]:
py_list = [1,2,3]
print('Python list multiplication: ', py_list * 2)

np_array = np.array([1,2,3]) # Element wise multiplication
print('Python array multiplication: ', np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print('\nList operation  time: ', time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print('\nNumpy operation time: ', time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]



List operation  time:  0.23767423629760742

Numpy operation time:  0.004475593566894531


Creating array from scratch

In [6]:
zeros = np.zeros((3,4))
print('Zeros array: \n', zeros)

ones = np.ones((2,3))
print('One array: \n', ones)

full = np.full((2,2), 7)
print('Full array: \n', full)

random = np.random.random((2,3))
print('Random array: \n', random)

sequence = np.arange(0, 11, 2)
print('Sequence array: \n', sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.6633671  0.50146624 0.68714582]
 [0.03627979 0.33792014 0.22291525]]
Sequence array: 
 [ 0  2  4  6  8 10]


Vector, Matrix and Tensor

In [7]:
vector = np.array([1,2,3])
print('Vector: ', vector)

matrix = np.array([[1,2,3], 
                  [4,5,6]])
print('\nMatrix: \n', matrix)

tensor = np.array([[[1,2], [3,4]], 
                    [[5,6], [7,8]]])
print('\nTensor: \n', tensor)

Vector:  [1 2 3]

Matrix: 
 [[1 2 3]
 [4 5 6]]

Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [8]:
arr = np.array([[1,2,3],
                [4,5,6]])
print('Shape ', arr.shape)
print('Dimension ', arr.ndim)
print('Size ', arr.size)
print('DType ', arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


Array Reshaping


In [9]:
arr = np.arange(12)
print(' Original array ', arr)

reshaped = arr.reshape((3, 4))
print('\n Reshaped array \n', reshaped)

flattened = reshaped.flatten()
print('\n Flattened array ', flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print('\n Raveled array ', raveled)

# transpose
transpose = reshaped.T
print('\n Transposed array \n', transpose)

 Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
